### ISSUE TITLE
Error with message "loglikelihood: nan"

### ISSUE THREAD

**Issue by zhaoxiaofei** [NielsenBerkeleyLab/sconce#1]
Hi there,

I tried running sconce on some low-depth WGS scDNA-seq data, and I ran into this error: 

```
loglikelihood: -165802.5274186880

lambda_ij = ploidy_ij * 2.550294 * mu_i/2 + mu_i/50
X_ij ~ NegBinom(mean=lambda_ij, variance=14.763891 + 163.530708*lambda_ij + 0.000968*lambda_ij^2)

Starting AllCells3TrParam2DegPolyHMM::setBaumWelchInitGuess, with libMultiplier 4 (RUN 3 OF 3)
HMM 0 (SRR927014):
transition matrix:
        0       1       2       3       4       5
0       0.9949414876    0.003970114826  0.0006563811824         0.000243054052  0.0001118400206         7.712236328e-05
1       0.001729913054  0.9945116853    0.003328800467  0.0002159635805         0.0001382784472         7.535916647e-05
2       0.0001460643019         0.00170002192   0.996202706     0.001690527688  0.0001277217954         0.0001329582564
3       0.0001063187149         0.0002168034375         0.003323082899  0.9946397766    0.001571546811  0.0001424715687
4       0.0001200301141         0.0003405855878         0.0006159848485         0.00385579068   0.993212552     0.001855056724
5       0.0001330554821         0.0002983783595         0.001030812768  0.0005619191038         0.002982061923  0.9949937724

initProb vector:
0       0.0863092566047376774651667119542253203690
1       0.1980779660731676050655636345254606567323
2       0.3878550142891794560995322171947918832302
3       0.1973106481416160018493854977350565604866
4       0.0804200605013260932940610814512183424085
5       0.0500270543899730898984579141597350826487

paramsToEst:
6.6648251332915577904714155010879039764404
0.0100000000000000002081668171172168513294
500.0000000000000000000000000000000000000000
0.0100000000000000002081668171172168513294

fixedParams:
0.1000000000000000055511151231257827021182

loglikelihood: nan

lambda_ij = ploidy_ij * 6.664825 * mu_i/2 + mu_i/50
X_ij ~ NegBinom(mean=lambda_ij, variance=14.763891 + 163.530708*lambda_ij + 0.000968*lambda_ij^2)

STARTING BAUM WELCH for HMM 0, WITH LIBMULTIPLIER 4 (RUN 3 OF 3)
BAUM WELCH INITIAL LIKELIHOOD: nan
ERROR: forward loglikelihood (nan) or backward loglikelihood (nan) is nan. Stopping.
ERROR: problem wtih forward/backward algorithm. Breaking out of baum welch
BAUM WELCH INDV HMM LOGLIKELIHOOD FOUND: 0.0000000000000000000000000000000000000000
CHANGE IN BAUM WELCH INDV HMM LIKELIHOOD: nan
BAUM WELCH INDV HMM TIME (sec): 0.0000000000
DONE WITH BAUM WELCH INDV HMM.

gsl: ../gsl/gsl_matrix_double.h:282: ERROR: first index out of range
Default GSL error handler invoked.
Aborted
```

Do you know what to do to correct this error?

**Comment by avaughn271** [comment]
Unfortunately, the main developer of sconce has since left the lab, so we are unable to provide answers to specific code questions. My guess is that since it is an indexing error, something about the data you're running sconce on has triggered an edge case or is otherwise unable to be properly parsed. Sorry I can't provide more help than that.

**Comment by zhaoxiaofei** [comment]
@avaughn271  Thank you for your answer. It looks like bed region with zero depth is the reason to trigger this bug. I figured out a workaround to solve this problem: perform add-one smoothing (Let depth=depth+1 for all bed regions) so that no bed region has a depth of zero.  The results looks OK so far.

**Comment by zhaoxiaofei** [comment]
I found a workaround, so this issue is closed.

**Comment by zhaoxiaofei** [comment]
Actually sconce still does not work as intended: I got segfault for both sconce and sconce2. 


65062808990     7762.0467182655065698781982064247131347656250
ERROR: params resulted in uniform transition matrix in baumWelchLeastSquares_f  |       4.2038286626529997036527674936223775148392      8.1319488691450523276671447092667222023010     7762.8229617488586882245726883411407470703125
OPTIMINDCELLS BW+LS TOTAL TIME (sec): 33.19481
STARTING OPTIMINDCELLS BFGS SET UP
CALLING BFGS, RUN 1 OF 1 PLANNED, USING INITGUESS:
2.4400464183170931242727874632691964507103      0.0161385703510142017313988560545112704858      5739.5905832534308501635678112506866455078125   0.4068702965491538536824123184487689286470

BEST OVERALL BFGS LIKELIHOOD (FROM RUN 1): -132935.5577312837413046509027481079101562500000
BEST BFGS PARAMS:
2.5330535823015507546074331912677735090256
0.0011527829802912149381038942053123719234
9982.2179360437094146618619561195373535156250
0.1954650809119021226401002877537393942475

Segmentation fault


Since the main developer has left, I guess there is no way to fix the error, so I will just close this issue again.
